server:
  port: 8081

spring:

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: EMBEDDED

#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

    show-sql: true

#logging:
#  level:
#    org:
#      springframework: OFF
#    root: OFF